//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18408
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageAdministerExalt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQLite")]
        public global::WebDaD.Toolkit.Database.DatabaseType db_type {
            get {
                return ((global::WebDaD.Toolkit.Database.DatabaseType)(this["db_type"]));
            }
            set {
                this["db_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string db_connection_string {
            get {
                return ((string)(this["db_connection_string"]));
            }
            set {
                this["db_connection_string"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string basepath {
            get {
                return ((string)(this["basepath"]));
            }
            set {
                this["basepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SimBA")]
        public string app_name {
            get {
                return ((string)(this["app_name"]));
            }
            set {
                this["app_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string license_key {
            get {
                return ((string)(this["license_key"]));
            }
            set {
                this["license_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tab_reports")]
        public string default_tab {
            get {
                return ((string)(this["default_tab"]));
            }
            set {
                this["default_tab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>tab_customers</string>
  <string>tab_worker</string>
  <string>tab_jobs</string>
  <string>tab_reports</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection active_tabs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["active_tabs"]));
            }
            set {
                this["active_tabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("worker|mitarbeiter;customer|kunde;discount|rabatt;expense|ausgabe;item|Gegenstand" +
            ";job|auftrag;paymentcondition|zahlungsbedingung;reminder|Mahnung;service|leistun" +
            "g;term|agb;\r\n")]
        public string paths {
            get {
                return ((string)(this["paths"]));
            }
            set {
                this["paths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bill|B%ID5%;customer|C%ID5%;discount|D%ID5%;expense|E%ID5%;item|I%ID5%;job|J%ID5%" +
            ";paymentcondition|P%ID5%;reminder|R%ID5%;sevrice|S%ID5%;term|§ %ID2%;worker|W%ID" +
            "5%;")]
        public string idformating {
            get {
                return ((string)(this["idformating"]));
            }
            set {
                this["idformating"] = value;
            }
        }
    }
}
